-- Seed postcode area to region mapping.

INSERT INTO postcode_regions (postcode_area, region, region_group) VALUES
    ('E',   'London', 'London'),
    ('EC',  'London', 'London'),
    ('N',   'London', 'London'),
    ('NW',  'London', 'London'),
    ('SE',  'London', 'London'),
    ('SW',  'London', 'London'),
    ('W',   'London', 'London'),
    ('WC',  'London', 'London'),
    ('BN',  'South East', 'South'),
    ('BR',  'South East', 'South'),
    ('CM',  'South East', 'South'),
    ('CR',  'South East', 'South'),
    ('CT',  'South East', 'South'),
    ('DA',  'South East', 'South'),
    ('EN',  'South East', 'South'),
    ('GU',  'South East', 'South'),
    ('HA',  'South East', 'South'),
    ('HP',  'South East', 'South'),
    ('IG',  'South East', 'South'),
    ('KT',  'South East', 'South'),
    ('LU',  'South East', 'South'),
    ('ME',  'South East', 'South'),
    ('MK',  'South East', 'South'),
    ('OX',  'South East', 'South'),
    ('PO',  'South East', 'South'),
    ('RG',  'South East', 'South'),
    ('RH',  'South East', 'South'),
    ('RM',  'South East', 'South'),
    ('SG',  'South East', 'South'),
    ('SL',  'South East', 'South'),
    ('SM',  'South East', 'South'),
    ('SS',  'South East', 'South'),
    ('TN',  'South East', 'South'),
    ('TW',  'South East', 'South'),
    ('UB',  'South East', 'South'),
    ('WD',  'South East', 'South'),
    ('BA',  'South West', 'South'),
    ('BH',  'South West', 'South'),
    ('BS',  'South West', 'South'),
    ('DT',  'South West', 'South'),
    ('EX',  'South West', 'South'),
    ('GL',  'South West', 'South'),
    ('PL',  'South West', 'South'),
    ('SN',  'South West', 'South'),
    ('SP',  'South West', 'South'),
    ('TA',  'South West', 'South'),
    ('TQ',  'South West', 'South'),
    ('TR',  'South West', 'South'),
    ('AL',  'East of England', 'South'),
    ('CB',  'East of England', 'South'),
    ('CO',  'East of England', 'South'),
    ('IP',  'East of England', 'South'),
    ('NR',  'East of England', 'South'),
    ('PE',  'East of England', 'South'),
    ('DE',  'East Midlands', 'Midlands'),
    ('DN',  'East Midlands', 'Midlands'),
    ('LE',  'East Midlands', 'Midlands'),
    ('LN',  'East Midlands', 'Midlands'),
    ('NG',  'East Midlands', 'Midlands'),
    ('NN',  'East Midlands', 'Midlands'),
    ('B',   'West Midlands', 'Midlands'),
    ('CV',  'West Midlands', 'Midlands'),
    ('DY',  'West Midlands', 'Midlands'),
    ('HR',  'West Midlands', 'Midlands'),
    ('ST',  'West Midlands', 'Midlands'),
    ('SY',  'West Midlands', 'Midlands'),
    ('TF',  'West Midlands', 'Midlands'),
    ('WR',  'West Midlands', 'Midlands'),
    ('WS',  'West Midlands', 'Midlands'),
    ('WV',  'West Midlands', 'Midlands'),
    ('BB',  'North West', 'North'),
    ('BL',  'North West', 'North'),
    ('CA',  'North West', 'North'),
    ('CH',  'North West', 'North'),
    ('CW',  'North West', 'North'),
    ('FY',  'North West', 'North'),
    ('L',   'North West', 'North'),
    ('LA',  'North West', 'North'),
    ('M',   'North West', 'North'),
    ('OL',  'North West', 'North'),
    ('PR',  'North West', 'North'),
    ('SK',  'North West', 'North'),
    ('WA',  'North West', 'North'),
    ('WN',  'North West', 'North'),
    ('BD',  'Yorkshire and the Humber', 'North'),
    ('HD',  'Yorkshire and the Humber', 'North'),
    ('HG',  'Yorkshire and the Humber', 'North'),
    ('HU',  'Yorkshire and the Humber', 'North'),
    ('HX',  'Yorkshire and the Humber', 'North'),
    ('LS',  'Yorkshire and the Humber', 'North'),
    ('S',   'Yorkshire and the Humber', 'North'),
    ('WF',  'Yorkshire and the Humber', 'North'),
    ('YO',  'Yorkshire and the Humber', 'North'),
    ('DH',  'North East', 'North'),
    ('DL',  'North East', 'North'),
    ('NE',  'North East', 'North'),
    ('SR',  'North East', 'North'),
    ('TS',  'North East', 'North'),
    ('CF',  'Wales', 'Wales'),
    ('LD',  'Wales', 'Wales'),
    ('LL',  'Wales', 'Wales'),
    ('NP',  'Wales', 'Wales'),
    ('SA',  'Wales', 'Wales'),
    ('AB',  'Scotland', 'Scotland'),
    ('DD',  'Scotland', 'Scotland'),
    ('DG',  'Scotland', 'Scotland'),
    ('EH',  'Scotland', 'Scotland'),
    ('FK',  'Scotland', 'Scotland'),
    ('G',   'Scotland', 'Scotland'),
    ('HS',  'Scotland', 'Scotland'),
    ('IV',  'Scotland', 'Scotland'),
    ('KA',  'Scotland', 'Scotland'),
    ('KW',  'Scotland', 'Scotland'),
    ('KY',  'Scotland', 'Scotland'),
    ('ML',  'Scotland', 'Scotland'),
    ('PA',  'Scotland', 'Scotland'),
    ('PH',  'Scotland', 'Scotland'),
    ('TD',  'Scotland', 'Scotland'),
    ('ZE',  'Scotland', 'Scotland'),
    ('BT',  'Northern Ireland', 'Northern Ireland')
ON CONFLICT (postcode_area) DO NOTHING;
